# Copyright (C) 2007  Marcel Unbehaun <frostworks@gmx.de>
# Copyright (C) 2007  Miriam Ruiz <little_miry@yahoo.es>
# Distributed under the same license as the game. See debian/copyright.

Index: tumiki-fighters-0.2.dfsg1/Makefile
===================================================================
--- /dev/null	1970-01-01 00:00:00.000000000 +0000
+++ tumiki-fighters-0.2.dfsg1/Makefile	2007-09-08 17:35:31.000000000 +0000
@@ -0,0 +1,32 @@
+DC=gdmd-v1
+#DC=gdc
+ifeq ($(DC), gdmd-v1)
+DFLAGS=-g -debug -O
+#DFLAGS=-g -debug
+DOUT=-of
+else
+DFLAGS=-O -debug
+#DFLAGS=-g -fdebug
+DOUT=-o
+endif
+
+DSRC=$(shell find src/ -name "*.d")
+SOURCES=$(DSRC) import/SDL_video.d import/SDL_mixer.d
+OBJS=$(SOURCES:.d=.o)
+EXE=tumiki-fighters
+
+all: $(EXE)
+
+$(EXE): $(OBJS)
+	gdc-v1 -o $@ $(OBJS) -lbulletml -lSDL -lGL -lSDL_mixer
+
+$(OBJS): %.o: %.d
+	gdmd-v1 -d -c -of$@ $(DFLAGS) -Iimport -Isrc $<
+
+clean:
+	$(RM) src/*.o
+	$(RM) src/abagames/tf/*.o
+	$(RM) src/abagames/util/*.o
+	$(RM) src/abagames/util/sdl/*.o
+	$(RM) src/abagames/util/bulletml/*.o
+	$(RM) import/*.o
