language: ruby
before_script: 
  - sudo apt-get -qq update 
  - sudo apt-get source tumiki
  - git clone https://github.com/brownman/travis_screenacast
  - cd travis_screencast
  - ./travis.sh
  
after_script:
  - echo done
