language: python 
cache: apt
 
env:
  global:
    #secure: "UoWHJNW/YXhHHBdjJ9pQCrPQa1WLc24s8kxpgF5bOCAZbRLLh7ndVoLLpsMdf9XCbTw/42RpYFrhag8oLwNn2cqAHBV38A32vAodwt6TGjGlEqM7oNTllikGOolEo4XAkldULcG2dHa22oQjUqqrcFVu0AiPcOCJs7/BC5aalF8="
    secure: "andQW/weSd+Tl8ejxsXjQcp7aQGe1pUqpE7idSztlvIDwiO5MiLSQCIdoKQlxEMDh19vSOXH7KqkIn9ao9XL6/teCZBQ9XxsYdFT93568nCfUSzAM60Gtrp2ynmWsPEP39zM2O7b1JZ8nCVoa1RYqrBMmpaRoecXnCTOcq7LLyM="



  #  secure: "eeg3fbZ+021Nwb519WvJ6jBWJxQzepJAq/kPRCQgP7JgWadWcSuOukn+aN+Dij7T8Wks+PRZGsPN91Xh4keKOnlPSBme7wK8pt0osFpy2fdX9KCj6gOp0/+cpRrkpomdSo+hX1iNdqJcFjP8OtMtC08Vs0mTbjzN2OaPtEfuXGU="



matrix:
  fast_finish: true
  
# whitelist
branches:
  only:
    - game

before_install:
  - echo before install
  - export owner=brownman
  - export repo=tumiki-fighters
  #- export MODE_EXTERNAL=false
  - export MODE_EXTERNAL=true
  #true
  #- export task_external=''
  - export task_external=/home/travis/build/brownman/tumiki-fighters/tumiki.sh
  ############################# TEST BEFORE INSTALL :
#  - sudo apt-get -qq update 
#  - sudo apt-get source tumiki-fighters
  - chmod u+x *.sh . -R
  - $task_external install
#  - exit 0
  #######



  
install: 
  - git clone --depth=1 --branch=develop https://github.com/brownman/travis_screencast
  - chmod u+x *.sh . -R
  - cd travis_screencast
  - echo let us start  
  - mkdir /tmp/log
  - mkdir /tmp/PRODUCT
  - ./travis.sh


 
before_script:
  - echo before_script

script:
  - echo script1
  
after_script:
  - echo after_script

after_success:
  - echo after_success


after_failure:
  - echo after_failure
 # - ./run.sh push_to_github
